import "./globals.css";
import type { Metadata } from "next";
import { fontSans } from "#src/utils/font";
import { Init } from "./Init";
import { TrpcProvider } from "#src/context/Trpc";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={fontSans.variable}>
        <TrpcProvider>{children}</TrpcProvider>
      </body>
      <Init />
    </html>
  );
}
